#!/usr/bin/env node
// bootstrap.mjs — idempotent memory-tree bootstrap (realizes MEM-13 / DESIGN §6a.3).
//
// Safe to re-run: creates only what's missing, NEVER overwrites an existing file
// (so it can't clobber /watch's captured sources). Clone-clean (MEM-23/OSS-1): every
// path resolves relative to this script — no hardcoded absolute paths, no secrets.
//
// This script is the SOURCE OF TRUTH for the data-tree shape. The data dirs are
// gitignored from the public repo (OSS-1), so on a clone you run this to recreate them:
//   knowledge/nodes/        flat node pool — scope lives in frontmatter, not the path
//   knowledge/INDEX.md      reconciler-generated master index (placeholder until first run)
//   scopes/<scope>/{identity,log,staging,sources}/
//
// Seeds LIVE scopes only. Dormant ventures/clients are materialized by the SAME
// ensureScope() at re-onboarding (OPEN-7) — never blanket-seeded (clean-start, MEM-15).
// No vault/ dirs — isolation is the VM, not the graph (MEM-23).

import { mkdir, writeFile, access } from 'node:fs/promises';
import { constants } from 'node:fs';
import { dirname, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ENGINE_DIR = dirname(fileURLToPath(import.meta.url));   // ~/.cockpit/memory-engine (public system code)
const REPO_ROOT = resolve(ENGINE_DIR, '..');     // ~/.cockpit — for friendly logging only
export const MEMORY_ROOT = resolve(REPO_ROOT, 'memory');   // private DATA repo — also imported by capture.mjs

const LIVE_SCOPES = ['global', 'cockpit', 'content', 'job-search', 'boringscale'];
const SCOPE_DIRS = ['identity', 'log', 'staging', 'sources'];

const created = [];
const rel = (p) => relative(REPO_ROOT, p);

async function exists(p) {
  try { await access(p, constants.F_OK); return true; } catch { return false; }
}

async function ensureDir(p) {
  if (await exists(p)) return;
  await mkdir(p, { recursive: true });
  created.push(`dir  ${rel(p)}/`);
}

// Write a seed file ONLY if missing — never clobber existing content.
async function ensureFile(p, content) {
  if (await exists(p)) return;
  await mkdir(dirname(p), { recursive: true });
  await writeFile(p, content, 'utf8');
  created.push(`file ${rel(p)}`);
}

function identityStub(scope) {
  return `---
id: identity-${scope}
title: ${scope} — identity
type: identity
claim: inference
scope: ${scope}
schema_version: 1
---

_Identity stub for the **${scope}** scope. Filled by the reconciler (distillation) or grill-me
(active elicitation, DESIGN §8) — not hand-authored at bootstrap. Holds who this scope serves,
its voice/mission, and durable preferences once they exist._
`;
}

const SOUL = `---
id: soul
title: Operator meta-identity (Arn / Hermes)
type: identity
claim: inference
scope: global
schema_version: 1
---

_Operator meta-identity stub (DESIGN §3): the global-scope identity of the operator (Arn) and the
Hermes operator fleet — distinct from any per-context identity, which lives in that scope's
\`identity/\`. Filled by the reconciler / grill-me, never hand-authored at bootstrap. soul.md
mutations route through staging→reconciler (DESIGN §5), never direct writes._
`;

const INDEX = `<!-- generated by the reconciler — do not hand-edit (DESIGN §6a.3 / §7) -->
# Knowledge INDEX

Reconciler-generated master index: high-centrality god-nodes grouped by cluster, one line +
\`[[wikilink]]\` each. Regenerated every run.

_Empty — append-only bootstrap mode until ≥1 centroid node per cluster exists (DESIGN §6a.3)._
`;

export async function ensureScope(scope) {
  for (const d of SCOPE_DIRS) await ensureDir(resolve(MEMORY_ROOT, 'scopes', scope, d));
  // global's identity IS soul.md (DESIGN §3); other live scopes get a generic identity stub.
  if (scope === 'global') {
    await ensureFile(resolve(MEMORY_ROOT, 'scopes', 'global', 'identity', 'soul.md'), SOUL);
  } else {
    await ensureFile(resolve(MEMORY_ROOT, 'scopes', scope, 'identity', `${scope}.md`), identityStub(scope));
  }
}

async function main() {
  await ensureDir(resolve(MEMORY_ROOT, 'knowledge', 'nodes'));
  await ensureFile(resolve(MEMORY_ROOT, 'knowledge', 'INDEX.md'), INDEX);
  for (const scope of LIVE_SCOPES) await ensureScope(scope);

  if (created.length === 0) {
    console.log('bootstrap: tree already complete — no changes (idempotent).');
  } else {
    console.log(`bootstrap: created ${created.length} item(s):`);
    for (const c of created) console.log('  + ' + c);
  }
}

// Run only when invoked directly (so capture.mjs can import ensureScope without running this).
const invokedPath = process.argv[1] ? resolve(process.argv[1]) : '';
if (invokedPath === fileURLToPath(import.meta.url)) {
  main().catch((e) => { console.error('bootstrap failed:', e); process.exit(1); });
}
